# This is a basic workflow to help you get started with Actions

name: Checklist

# Controls when the workflow will run
on:
  # Triggers the workflow on pull requests
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "checklist"
  checklist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Changelog checker
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          # Changelog fileName
          fileName: docs/CHANGELOG.md
          # Label to ignore changelog check
          noChangelogLabel: Missing changelog
          # Simple or Detailed
          # checkNotification: # optional, default is Detailed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Include built project
        run: |
          import json
          with open("build/manifest.json") as fh:
            manifest = fh.read()
          with open("package.json") as fh:
            package = fh.read()
          manifest = json.loads(manifest)
          package = json.loads(package)
          if not ('version' in manifest.keys() and 'version' in package.keys()):
            exit(2)
          if manifest['version'] == package['version']:
            exit(0)
          exit(1)
        shell: python
